version: v4
tasks:
  - task_id: libero_spatial_black_bowl
    legacy_task_id: spatial_bowl_plate
    suite: libero_spatial
    task_name: pick_up_the_black_bowl_between_the_plate_and_the_ramekin_and_place_it_on_the_plate
    dataset_path: ${LIBERO_DATA_ROOT}/libero_spatial/pick_up_the_black_bowl_between_the_plate_and_the_ramekin_and_place_it_on_the_plate_demo.hdf5
    max_steps: 400
    default_unnorm_key: libero_spatial
  - task_id: libero_object_alphabet_soup
    legacy_task_id: object_alphabet_soup
    suite: libero_object
    task_name: pick_up_the_alphabet_soup_and_place_it_in_the_basket
    dataset_path: ${LIBERO_DATA_ROOT}/libero_object/pick_up_the_alphabet_soup_and_place_it_in_the_basket_demo.hdf5
    max_steps: 400
    default_unnorm_key: libero_object
  - task_id: libero_goal_open_middle_drawer
    legacy_task_id: goal_open_middle_drawer
    suite: libero_goal
    task_name: open_the_middle_drawer_of_the_cabinet
    dataset_path: ${LIBERO_DATA_ROOT}/libero_goal/open_the_middle_drawer_of_the_cabinet_demo.hdf5
    max_steps: 400
    default_unnorm_key: libero_goal
  - task_id: libero10_moka_pots
    legacy_task_id: long_two_moka_pots
    suite: libero_10
    task_name: KITCHEN_SCENE8_put_both_moka_pots_on_the_stove
    dataset_path: ${LIBERO_DATA_ROOT}/libero_10/KITCHEN_SCENE8_put_both_moka_pots_on_the_stove_demo.hdf5
    max_steps: 700
    default_unnorm_key: libero_10
